# Generated by Django 5.2.11 on 2026-09-24 09:18
#
# Includes the `AnalyticsWatermark.address` field the P2 nightly rollup task
# needs (the `erc20_balance_safes` seed marker, an ordered `(created,
# address)` pair -- see `analytics/tasks.py`). Folded in here rather than a
# separate `0011_*` migration: neither has shipped yet and the whole feature
# lands as one cherry-picked commit, so one migration for it is simpler than
# two.

import safe_eth.eth.django.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_catchup_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticswatermark',
            name='address',
            field=safe_eth.eth.django.models.EthereumAddressBinaryField(
                blank=True, default=None, null=True
            ),
        ),
        migrations.CreateModel(
            name='Erc20BalanceWhale',
            fields=[
                ('safe_address', safe_eth.eth.django.models.EthereumAddressBinaryField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TokenHolding',
            fields=[
                ('token_address', safe_eth.eth.django.models.EthereumAddressBinaryField(primary_key=True, serialize=False)),
                ('holders', models.PositiveIntegerField(default=0)),
                ('negative_pairs', models.PositiveIntegerField(default=0)),
                ('total_balance', models.DecimalField(decimal_places=0, default=0, max_digits=1000)),
                ('as_of_block', models.PositiveIntegerField()),
                ('as_of_timestamp', models.DateTimeField()),
                ('computed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SafeTokenBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safe_address', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('token_address', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('balance', models.DecimalField(decimal_places=0, max_digits=1000)),
            ],
            options={
                'indexes': [models.Index(fields=['token_address'], name='analytics_stb_token_idx')],
                'constraints': [models.UniqueConstraint(fields=('safe_address', 'token_address'), name='analytics_safe_token_balance_uniq')],
            },
        ),
    ]
