# Generated by Django 5.2.11 on 2026-09-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_token_holdings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsBootstrapStage',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_dispatch_at', models.DateTimeField(blank=True, null=True)),
                ('gave_up_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_depth', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
